/**
 * plugins/vuetify.ts
 *
 * Framework documentation: https://vuetifyjs.com`
 */

// Styles
import '@mdi/font/css/materialdesignicons.css'
import 'vuetify/styles'

// Composables
import { createVuetify } from 'vuetify'
const myCustomDarkTheme = {
  dark: true,
  colors: {
    "primary": "#b8c1ec",
    accent: "#121629",
    "surfaceTint": "#BCC5F0",
    "onPrimary": "#121629",
    "primaryContainer": "#B8C1EC",
    "onPrimaryContainer": "#454E73",
    "secondary": "#FFFFFe",
    "onSecondary": "#121629",
    "secondaryContainer": "#E2E2E2",
    "onSecondaryContainer": "#636564",
    "tertiary": "#eebbc3",
    "onTertiary": "#232946",
    "tertiaryContainer": "#EEBBC3",
    "onTertiaryContainer": "#6F4950",
    "error": "#ba1a1a",
    "onError": "#690005",
    "errorContainer": "#93000A",
    "onErrorContainer": "#FFDAD6",
    "background": "#232946",
    "onBackground": "#fffffe",
    "surface": "#131315",
    "onSurface": "#E5E1E4",
    "surfaceVariant": "#504445",
    "onSurfaceVariant": "#D4C2C4",
    "outline": "#9C8D8F",
    "outlineVariant": "#504445",
    "shadow": "#000000",
    "scrim": "#000000",
    "inverseSurface": "#E5E1E4",
    "inverseOnSurface": "#303032",
    "inversePrimary": "#545D82",
    "primaryFixed": "#DCE1FF",
    "onPrimaryFixed": "#0F193B",
    "primaryFixedDim": "#BCC5F0",
    "onPrimaryFixedVariant": "#3C4569",
    "secondaryFixed": "#E2E2E2",
    "onSecondaryFixed": "#1A1C1C",
    "secondaryFixedDim": "#C6C7C6",
    "onSecondaryFixedVariant": "#454747",
    "tertiaryFixed": "#FFD9DE",
    "onTertiaryFixed": "#2F1219",
    "tertiaryFixedDim": "#ECBAC2",
    "onTertiaryFixedVariant": "#613C43",
    "surfaceDim": "#131315",
    "surfaceBright": "#39393B",
    "surfaceContainerLowest": "#0E0E10",
    "surfaceContainerLow": "#1B1B1E",
    "surfaceContainer": "#1F1F22",
    "surfaceContainerHigh": "#2A2A2C",
    "surfaceContainerHighest": "#353437"
  },
}
const myCustomLightTheme = {
  dark: false,
  colors: {
    "primary": "#545D82",
    "surfaceTint": "#545D82",
    "onPrimary": "#FFFFFF",
    "primaryContainer": "#B8C1EC",
    "onPrimaryContainer": "#454E73",
    "secondary": "#5D5F5E",
    "onSecondary": "#FFFFFF",
    "secondaryContainer": "#FFFFFE",
    "onSecondaryContainer": "#747675",
    "tertiary": "#7B545B",
    "onTertiary": "#FFFFFF",
    "tertiaryContainer": "#EEBBC3",
    "onTertiaryContainer": "#6F4950",
    "error": "#BA1A1A",
    "onError": "#FFFFFF",
    "errorContainer": "#FFDAD6",
    "onErrorContainer": "#93000A",
    "background": "#FBF8FC",
    "onBackground": "#1B1B1E",
    "surface": "#FCF8FB",
    "onSurface": "#1B1B1E",
    "surfaceVariant": "#F1DEE0",
    "onSurfaceVariant": "#504445",
    "outline": "#827475",
    "outlineVariant": "#D4C2C4",
    "shadow": "#000000",
    "scrim": "#000000",
    "inverseSurface": "#303032",
    "inverseOnSurface": "#F3F0F3",
    "inversePrimary": "#BCC5F0",
    "primaryFixed": "#DCE1FF",
    "onPrimaryFixed": "#0F193B",
    "primaryFixedDim": "#BCC5F0",
    "onPrimaryFixedVariant": "#3C4569",
    "secondaryFixed": "#E2E2E2",
    "onSecondaryFixed": "#1A1C1C",
    "secondaryFixedDim": "#C6C7C6",
    "onSecondaryFixedVariant": "#454747",
    "tertiaryFixed": "#FFD9DE",
    "onTertiaryFixed": "#2F1219",
    "tertiaryFixedDim": "#ECBAC2",
    "onTertiaryFixedVariant": "#613C43",
    "surfaceDim": "#DCD9DC",
    "surfaceBright": "#FCF8FB",
    "surfaceContainerLowest": "#FFFFFF",
    "surfaceContainerLow": "#F6F3F6",
    "surfaceContainer": "#F0EDF0",
    "surfaceContainerHigh": "#EAE7EA",
    "surfaceContainerHighest": "#E5E1E4"
  },
}
// https://vuetifyjs.com/en/introduction/why-vuetify/#feature-guides
export default createVuetify({
  theme: {
    defaultTheme: 'myCustomDarkTheme',
    themes: {
      myCustomLightTheme,
      myCustomDarkTheme,
    },
  },
})
