/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDialog: typeof import('./components/AddDialog.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    BaseCard: typeof import('./components/BaseCard.vue')['default']
    ErrorDialog: typeof import('./components/ErrorDialog.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
